### ISSUE TITLE
Fate chart and scene alteration errors with vaesen system

### ISSUE THREAD

**Issue by bayang** [saif-ellafi/foundryvtt-mythic-gme#26]
same cause as https://github.com/saif-ellafi/foundryvtt-mythic-gme/issues/3 I guess but with https://github.com/fvtt-fria-ligan/vaesen-foundry-vtt

Foundry 9.280, Mythic 2.5.13, vaesen 2.3.6 (latest for v9)

I don't know enough how foundry works yet to be able to help.

Only two modules activated : dice so nice and Mythic GME (problem happens also without dice so nice)

Nothing happens in chat.

Errors are : 
```
foundry.js:319 Error: Unable to recreate Roll instance from provided data
    at Roll.fromJSON (foundry.js:7554:23)
    at get roll [as roll] (foundry.js:14989:27)
    at ChatMessage._renderRollContent (foundry.js:15333:73)
    at ChatMessage.getHTML (foundry.js:15284:18)
    at ChatLog.postOne (foundry.js:57887:32)
    at ChatMessage._onCreate (foundry.js:15357:12)
    at ClientDatabaseBackend.callback (foundry.js:10093:11)
    at foundry.js:10043:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:10043:33)
onError @ foundry.js:319
get roll @ foundry.js:14992
_renderRollContent @ foundry.js:15333
getHTML @ foundry.js:15284
postOne @ foundry.js:57887
_onCreate @ foundry.js:15357
callback @ foundry.js:10093
(anonymous) @ foundry.js:10043
_handleCreateDocuments @ foundry.js:10043
_createDocuments @ foundry.js:9939
await in _createDocuments (async)
create @ backend.mjs:96
await in create (async)
createDocuments @ document.mjs:338
create @ document.mjs:439
toMessage @ foundry.js:7441
callback @ mythic-gme-tools.js:1037
submit @ foundry.js:44151
_onClickButton @ foundry.js:44114
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:319 Error: Unable to recreate Roll instance from provided data
    at Roll.fromJSON (foundry.js:7554:23)
    at get roll [as roll] (foundry.js:14989:27)
    at main.js:205:49
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10105:13)
    at foundry.js:10043:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:10043:33)
    at ClientDatabaseBackend._createDocuments (foundry.js:9939:17)
onError @ foundry.js:319
get roll @ foundry.js:14992
(anonymous) @ main.js:205
_call @ foundry.js:294
callAll @ foundry.js:253
callback @ foundry.js:10105
(anonymous) @ foundry.js:10043
_handleCreateDocuments @ foundry.js:10043
_createDocuments @ foundry.js:9939
await in _createDocuments (async)
create @ backend.mjs:96
await in create (async)
createDocuments @ document.mjs:338
create @ document.mjs:439
toMessage @ foundry.js:7441
callback @ mythic-gme-tools.js:1037
submit @ foundry.js:44151
_onClickButton @ foundry.js:44114
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:297 Foundry VTT | Error thrown in hooked function '' for hook 'createChatMessage'
_call @ foundry.js:297
callAll @ foundry.js:253
callback @ foundry.js:10105
(anonymous) @ foundry.js:10043
_handleCreateDocuments @ foundry.js:10043
_createDocuments @ foundry.js:9939
await in _createDocuments (async)
create @ backend.mjs:96
await in create (async)
createDocuments @ document.mjs:338
create @ document.mjs:439
toMessage @ foundry.js:7441
callback @ mythic-gme-tools.js:1037
submit @ foundry.js:44151
_onClickButton @ foundry.js:44114
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
foundry.js:319 TypeError: Cannot read properties of null (reading 'dice')
    at main.js:235:14
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at ClientDatabaseBackend.callback (foundry.js:10105:13)
    at foundry.js:10043:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:10043:33)
    at ClientDatabaseBackend._createDocuments (foundry.js:9939:17)
    at async ChatMessage.createDocuments (document.mjs:338:21)
    at async ChatMessage.create (document.mjs:439:21)
onError @ foundry.js:319
_call @ foundry.js:298
callAll @ foundry.js:253
callback @ foundry.js:10105
(anonymous) @ foundry.js:10043
_handleCreateDocuments @ foundry.js:10043
_createDocuments @ foundry.js:9939
await in _createDocuments (async)
create @ backend.mjs:96
await in create (async)
createDocuments @ document.mjs:338
create @ document.mjs:439
toMessage @ foundry.js:7441
callback @ mythic-gme-tools.js:1037
submit @ foundry.js:44151
_onClickButton @ foundry.js:44114
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
backend.mjs:306 Foundry VTT | Created ChatMessage with id [yXgxlHoP8CCkgPfD]
foundry.js:15333 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'total')
    at ChatMessage._renderRollContent (foundry.js:15333:78)
    at ChatMessage.getHTML (foundry.js:15284:18)
    at ChatLog.postOne (foundry.js:57887:32)
    at ChatMessage._onCreate (foundry.js:15357:12)
    at ClientDatabaseBackend.callback (foundry.js:10093:11)
    at foundry.js:10043:43
    at Array.map (<anonymous>)
    at ClientDatabaseBackend._handleCreateDocuments (foundry.js:10043:33)
    at ClientDatabaseBackend._createDocuments (foundry.js:9939:17)
    at async ChatMessage.createDocuments (document.mjs:338:21)
```

![Screenshot_20220929_132802](https://user-images.githubusercontent.com/11558944/193020935-be033f48-01ae-45fc-9b8f-abb311e54159.png)

![Screenshot_20220929_132824](https://user-images.githubusercontent.com/11558944/193021003-1b256b44-aa29-4b20-86ab-78025e57e0c0.png)

**Comment by saif-ellafi** [comment]
Hey @bayang 

Just checked, the issue is on Vaesen side. They have fixed it for Foundry V10.
If you go to them, tell them that this code snippet is throwing errors
```js
let r = new Roll("1d100");
r.toMessage({});
```

Can't do nothing about this, unfortunately
JV

**Comment by bayang** [comment]
Ok @saif-ellafi  thnaks for having a look, I confirm it works fine on v10 : I'll just switch to v10.
